<?php require 'templates/layout/header.phtml' ?>

<!-- formulario de alta de tarea -->

	<?php if ($error): ?>
	<div class='alert alert danger' role='alert'>
		<?= $error ?>
	</div>
<?php endif ?>
<div class="container-xxl py-5">
        <div class="container">
            <div class="row g-4">
			<h3 align='center'>Loguin</h3>
 				<ul>
				<form action='login' method="POST" class="my-4">
					<div class="form-group">
						<label for='email'>Email</label>
						<input type='email' class='form-control' id='email' name='email' required>
					</div>
						<div class="form-group">
						<label for='password'>Password</label>
						<input type='password' class='form-control' id='password' name='password' required>
					</div>
    					<button type="submit" class='bnt btn-primary'>Login</button>
					</form> 
				</ul>
			</div>
    	</div>
	</div>					
