<?php require_once 'templates/header.phtml';
?>
<div class="container-xxl py-5">
        <div class="container">
            <div class="row g-4">
			<h3 align='center'>Alta de Eventos</h3>
 				<ul>
				<form action="agregar" method="POST" class="my-4">
					<div class="row">
						<div class="form-group">
							<label>Nombre</label>
						 		<input name="nombre" type="text" class="form-control" rows="3">
						</div>
        				<div class="form-group">
							<label>Descripcion</label>
								<textarea name="descripcion" class="form-control" rows="3"></textarea>
						</div>
        				<div class="form-group">
							<label>Fecha</label>
								<input name="fecha" type="date" class="form-control" rows="3">
						</div>
						<div class="form-group">
						<label>Tipo de Eventos</label>
							<select type="text" name="tipo" class="form-control" value="<?=$event->tipo?>">
							<?php foreach($tipos as $tipo): ?>	
                    		     		<option value="<?=$tipo->id?>"><?=$tipo->nombre?></option>
										 <?php endforeach?>
								</select>	                            
						</div>
    				<button type="submit" class="bnt btn-primary mt-2">Guardar</button>
					</div>
				</form>
				</ul>
			</div>
    	</div>
	</div>
    <?php
require_once 'templates/footer.phtml';