<?php require_once 'templates/header.phtml';
?>
<div class="container-xxl py-5">
        <div class="container">
            <div class="row g-4">
			<h3 align='center'>Alta de Tipo de Eventos</h3>
 				<ul>
				<form action="agregartipoevento" method="POST" class="my-4">
					<div class="row">
						<div class="form-group">
							<label>Tipo de Evento</label>
						 		<input name="nombre" type="text" class="form-control" rows="3">
						</div>
    				<button type="submit" class="bnt btn-primary mt-2">Guardar</button>
					</div>
				</form>
				</ul>
			</div>
    	</div>
	</div>
    <?php
require_once 'templates/footer.phtml';