<?php require_once 'templates/header.phtml';
?>
    <!-- Home -->
    <div class="container-fluid bg-light overflow-hidden my-5 px-lg-0">
        <div class="container about px-lg-0">
            <div class="row g-0 mx-lg-0">
                <div class="col-lg-6 ps-lg-0" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute img-fluid w-100 h-100" src="img/home2.jpg" style="object-fit: cover;" alt="">
                    </div>
                </div>
                <div class="col-lg-6 about-text py-5 wow fadeIn" data-wow-delay="0.5s">
                    <div class="p-lg-5 pe-lg-0">
                        <div class="section-title text-start">
                            <h1 class="display-5 mb-4">Espectáculos de Tandil</h1>
                        </div>
                        <p class="mb-4 pb-2">¡Shows, eventos, espectáculos, cine, teatro, conciertos, musicales y mucho más! Encontralos acá y elegí tu manera de seguir descubriendo y disfrutando de Tandil.</p>                      
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fin Home -->
    <?php      
require_once 'templates/footer.phtml';
?>