<?php
require 'templates/header.phtml';
?>
<div class='container-xxl py-5'>
     <div class='container'>
       <div class='row g-4'>
		<h3 align='center'>Editar Evento</h3>	
 		<ul>
			<form action="save/<?=$event->id?>" method="POST" class="my-4">
				<div class="row">
						<div class="form-group">
								<input id="id" name="id" type="hidden" value="<?=$event->id?>">
							<label>Nombre</label>
								<input type="text" name="nombre" class="form-control" rows="3" value="<?=$event->nombre?>">
						</div>
					<div class="form-group">
						<label>Descripcion</label>
							<input type="textarea" name="descripcion" class="form-control" rows="3" value="<?=$event->descripcion?>">
					</div>
					<div class="form-group">
						<label>Fecha</label>
							<input type="date" name="fecha" class="form-control" rows="3" value="<?=$event->fecha?>">
					</div>
					<div class="form-group">
						<label>Tipo de Eventos</label>
							<select name="tipo" id="tipo">
							<?php foreach($tipos as $tipo): ?>
								<?php if ($tipo->id == $event->tipo) : ?>	
                    		     		<option value="<?=$tipo->id?>" selected><?=$tipo->nombre?></option>
								<?php else : ?>
									<option value="<?=$tipo->id?>"><?=$tipo->nombre?></option>
									<?php endif ?>
										 <?php endforeach?>
								</select>	
					</div> 
    			<button type="submit" class="bnt btn-primary mt-2">Guardar</button>
				</div>
			</form>
		</ul>
       </div>
     </div>
</div>
<?php
require 'templates/footer.phtml';



