<?php
require 'templates/header.phtml';
?>
<div class='container-xxl py-5'>
     <div class='container'>
       <div class='row g-4'>
		<h3 align='center'>Editar Tipo Evento</h3>	
 		<ul>
			<form action="savetipoevent/<?=$tipoevent->id?>" method="POST" class="my-4">
				<div class="row">
						<div class="form-group">
								<input id="id" name="id" type="hidden" value="<?=$tipoevent->id?>">
							<label>Nombre</label>
								<input type="text" name="nombre" class="form-control" rows="3" value="<?=$tipoevent->nombre?>">
						</div>
    			<button type="submit" class="bnt btn-primary mt-2">Guardar</button>
				</div>
			</form>
		</ul>
       </div>
     </div>
</div>
<?php
require 'templates/footer.phtml';



